name: Taguatinga -> Rodoviária
on:
  workflow_dispatch:
  schedule:
    - cron: '0,30 9,10,11 * * 1-5'
    - cron: '0 9,10 * * 0,6'



jobs:
  trafficstatus2telegram:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Run Traffic Status 2 Telegram
        run: python trafficstatus.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          MESSAGE_DESTINATION: ${{ vars.MESSAGE_DESTINATION }}
          ORIGEM: Taguatinga, Brasília - DF
          DESTINO: Rodoviária Plano Piloto - Setor de Diversões Norte - Brasília, DF
          TITULO: ${{ github.workflow }}
